version: '3.8'
services:
  lux:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lux_shop
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
    - '3000:3000'
